import type { Metadata } from "next";
import { Fredoka, Signika } from 'next/font/google';
import "./globals.css";
import '../styles/variables.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const fredoka = Fredoka({
  subsets: ['latin'],
  variable: '--font-fredoka',
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

const signika = Signika({
  subsets: ['latin'],
  variable: '--font-signika',
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fredoka.variable} ${signika.variable}`}>
      <body style={{ fontFamily: 'var(--font-signika)' }}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
